#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
#org.gradle.configuration-cache=true
org.gradle.caching=true

# ? ????????? SOCKS-?????? ??? GRADLE
#systemProp.socksProxyHost=127.0.0.1
#systemProp.socksProxyPort=2080

# ????????? SOCKS ??? ????????? ????, ????? Gradle ?? ??????? ?????? ?????????? ?????? ? ????
#systemProp.socksNonProxyHosts=localhost|127.0.0.1

# ? ?????????? ????????? ANDROIDX ??? COMPOSE MULTIPLATFORM:
android.useAndroidX=true

# ? ????????? ????????? ??? ???????????? GRADLE, ??????? ?????? ERROR WRITING VALUE:
org.gradle.configuration-cache=false

# ????????? ??????????? ??????? ????????? ????????? ??????????
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true